### PR TITLE
Added Forge Multipart CBE Compatibility, crash fix

### LINKED ISSUE #128: Game crashes on riding facades attacthed to moving Slider Frames
I built a moving platform using Slider Frames to move some facades and the game crashes consistently when I try and stand on the moving parts.

funky-locomotion-1.12.2-1.1.1

### LINKED ISSUE #129: frame slider crash
I crash when I move one frame slider with another while trying to make an inchworm drive
[crash-2018-05-14_08.41.14-server.txt](https://github.com/rwtema/FunkyLocomotion/files/2001525/crash-2018-05-14_08.41.14-server.txt)

### LINKED ISSUE #130: crash when trying to move player
Game crashes when moving a player with frames, tested in a clean environment (only funky locomotion and thermal expansions to power to movers).
[crash report](https://github.com/rwtema/FunkyLocomotion/files/2020391/crash-2018-05-20_17.11.24-server.txt)
[log](https://github.com/rwtema/FunkyLocomotion/files/2020392/latest.log)

### PR DESCRIPTION
**Pull request by Mr-Smartguy**
* Added STICKY_BLOCK capability proxy for BlockMicropart
* Added move factory for BlockMultipart
* Fixed crash dependent on Forge version (isCollided/collided fields)

Fixes #130, Fixes #129, Fixes #128

### CODE REVIEW

**Comment by Mr-Smartguy** [comment]
Compiled jar here:
https://mega.nz/#!ATJBnJgZ!gWq7Apfl5zu_UYJlWXpwD0gc22riJ6cR4RssCPSy7-0

**Comment by malakai97** [comment]
I can confirm this fixes #130 

I did not test #128 or #129 

I'm still not able to craft mcmultipart blocks out of frame blocks, but I'm not entirely sure that's what the commits are meant to address.

**Comment by Mr-Smartguy** [comment]
You have to add the frame block to the mcmultipart config file to be able to cut it into parts. The parts then function as sticky blocks for the side that they occupy.

**Comment by venrob** [comment]
This totally needs to be merged

**Comment by erindalc** [comment]
This fixed my crash, thank you.

**Pull request merged**
