### PR TITLE
Fixed a crash with null pointer

### PR DESCRIPTION
**Pull request by Paulomart**

### CODE REVIEW

**Comment by 1Darco1** [comment]
@rwtema Please, look at this fix concerning a **super critical bug** in your Funky Locomotions mod. It's been reported over and over again, at least half of all the open issues here on Github are because of this **simple NPE**. I have to admit I have no understanding of your code whatsoever, but it's just a null check that's missing and it also **does not affect the flow** of the `startMoving` method (namely the surrounding for-each loop in line 234 - 245).

This bug has been around for way too long, and additionally, it shouldn't take much time to fix. If possible, merge this Pull request and release a new build ASAP. Thank you very much!

**Comment by Paulomart** [comment]
I don't think that this is the best the solution for the bug. The cause of this issue is deeper and is hard to fix, however this works..

**Comment by 1Darco1** [comment]
Call it a temporary workaround, then. To circumvent this and at least have a local fix, I've already tried to mainpulate the bytecode of the MovingManager.class file, but no luck so far. And recompiling just the one file also turns out to be tricky due to all the deps.

**Comment by Paulomart** [comment]
It's really simple, just run gradle on the command line

**Comment by KJP12** [comment]
Be nice if RWTema pushes a update that fixes that and NOT crash the entire game.

**Pull request closed without merging**
